language: python
branches:
  except:
  - gh-pages
matrix:
  include:
  - python: 3.6
    env: TOXENV=unit_py3,check
  - python: 3.7
    env: TOXENV=unit_py3,check
    dist: xenial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y enchant
install:
  - pip install --upgrade pip
  - pip install tox
script:
  - tox
