language: python
branches:
  except:
  - gh-pages
matrix:
  include:
  - python: 2.7
    env: TOXENV=unit_py2,check
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y enchant
install:
  - pip install --upgrade pip
  - pip install -r .travis.requirements.txt
script:
  - tox
