"""Add base job status fields.

Revision ID: 5b98aeabbf5e
Revises: b4dc33b1c274
Create Date: 2020-07-09 15:22:14.220409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b98aeabbf5e'
down_revision = 'b4dc33b1c274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('current_service', sa.String(length=16), nullable=True))
    op.add_column('job', sa.Column('data', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('errors', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('failed_service', sa.String(length=16), nullable=True))
    op.add_column('job', sa.Column('finish_time', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('prev_service', sa.String(length=16), nullable=True))
    op.add_column('job', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('state', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'state')
    op.drop_column('job', 'start_time')
    op.drop_column('job', 'prev_service')
    op.drop_column('job', 'finish_time')
    op.drop_column('job', 'failed_service')
    op.drop_column('job', 'errors')
    op.drop_column('job', 'data')
    op.drop_column('job', 'current_service')
    # ### end Alembic commands ###
