"""drop_username

Revision ID: 6a61895b8172
Revises: 44d247dd5a7c
Create Date: 2020-03-12 20:48:23.539827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a61895b8172'
down_revision = '44d247dd5a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=False))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    # ### end Alembic commands ###
