"""add ec2_subnet table

Revision ID: 89a2cf1d3255
Revises: 15d8a6b81095
Create Date: 2024-05-17 14:59:06.151233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from mash.services.database.extensions import db

# revision identifiers, used by Alembic.
revision = '89a2cf1d3255'
down_revision = '15d8a6b81095'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    # Generates the new table
    ec2_test_region_table = op.create_table('ec2_test_region',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('region', sa.String(length=32), nullable=False),
        sa.Column('subnet', sa.String(length=32), nullable=True),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['ec2_account.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    # Drops the new ec2_test_region table
    op.drop_table('ec2_test_region')
    # ### end Alembic commands ###
