"""Drop Azure account destination fields

Revision ID: c16a9ad64021
Revises: 5b98aeabbf5e
Create Date: 2021-01-13 13:02:57.946986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16a9ad64021'
down_revision = '5b98aeabbf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azure_account', 'destination_container')
    op.drop_column('azure_account', 'destination_resource_group')
    op.drop_column('azure_account', 'destination_storage_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_account', sa.Column('destination_storage_account', sa.VARCHAR(length=24), autoincrement=False, nullable=False))
    op.add_column('azure_account', sa.Column('destination_resource_group', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    op.add_column('azure_account', sa.Column('destination_container', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
