jwt_algorithm: HS256
jwt_secret: enter-a-secret
log_dir: /var/log/mash/
encryption_keys_file: /var/lib/mash/encryption_keys
ssh_private_key_file: /var/lib/mash/ssh_key
amqp_host: localhost
amqp_user: guest
amqp_pass: guest
smtp_host: localhost
smtp_port: 25
smtp_ssl: False
smtp_user: test@fake.com
credentials_url: http://localhost:5006/
database_api_url: http://localhost:5007/
database_uri: sqlite:////var/lib/mash/app.db
download_directory: /var/lib/mash/images
services:
  - download
  - upload
  - create
  - test_preparation
  - test
  - test_cleanup
  - raw_image_upload
  - replicate
  - publish
  - deprecate
credentials:
  credentials_directory: /var/lib/mash/credentials/
cloud:
  ec2:
    regions:
      aws:
        - af-south-1
        - ap-east-1
        - ap-northeast-1
        - ap-northeast-2
        - ap-south-1
        - ap-southeast-1
        - ap-southeast-2
        - ap-southeast-3
        - ca-central-1
        - eu-central-1
        - eu-north-1
        - eu-south-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - il-central-1
        - me-central-1
        - me-south-1
        - sa-east-1
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
      aws-cn:
        - cn-north-1
        - cn-northwest-1
      aws-us-gov:
        - us-gov-east-1
        - us-gov-west-1
    helper_images:
      af-south-1: ami-093ca241e4c72c205
      ap-east-1: ami-0e992f1e63814db10
      ap-northeast-1: ami-0828596b82405edd7
      ap-northeast-2: ami-087af0192368bc87c
      ap-southeast-1: ami-0ba98499caf94125a
      ap-southeast-2: ami-0849cc8fe4ceaf988
      ap-southeast-3: ami-0cf40308729b83366
      ap-south-1: ami-0400aca7799d8cf19
      ca-central-1: ami-0eb3718c42cb70e52
      cn-north-1: ami-0eb22e95b55ff11f8
      cn-northwest-1: ami-0e9ed4545da2f2c75
      eu-central-1: ami-0f7585ae7a0d9a25a
      eu-north-1: ami-0f58e72599cb99a79
      eu-south-1: ami-07b2af763a8b958f3
      eu-west-1: ami-047aad752a426ed48
      eu-west-2: ami-0dfe6158087b5c0ac
      eu-west-3: ami-064c70d04ad799d5e
      il-central-1: ami-056be49b9b86bc189
      me-central-1: ami-0384959b181e3642a
      me-south-1: ami-0a31e56929248acca
      sa-east-1: ami-0df67b3c17f090c24
      us-east-1: ami-0d52ddcdf3a885741
      us-east-2: ami-04148302a14f7d12b
      us-gov-east-1: ami-05146fa6cbcea4b79
      us-gov-west-1: ami-0e8f52046c02613e9
      us-west-1: ami-0ee3e1e65adeef858
      us-west-2: ami-0ec021424fb596d6c
    test_instance_catalog:
    - region: us-east-1
      partition: aws
      arch: x86_64
      instance_names:
      - c5.large
      - m5.large
      - t3.small
      boot_types:
        - uefi-preferred
        - uefi
      cpu_options: []
    - region: us-east-1
      arch: x86_64
      partition: aws
      instance_names:
      - i3.large
      - t2.small
      boot_types:
        - bios
      cpu_options: []
    - region: us-east-2
      partition: aws
      arch: x86_64
      instance_names:
      - m6a.large
      - c6a.large
      - r6a.large
      boot_types:
      - uefi-preferred
      - uefi
      cpu_options:
      - AmdSevSnp_enabled
    - region: us-east-1
      partition: aws
      arch: aarch64
      instance_names:
      - t4g.small
      - m6g.medium
      boot_types:
      - uefi
      - uefi-preferred
      cpu_options: []
    - region: cn-north-1
      partition: aws-cn
      arch: x86_64
      instance_names:
      - t3.small
      boot_types:
        - bios
      cpu_options: []
    - region: cn-north-1
      partition: aws-cn
      arch: x86_64
      instance_names:
      - m5.large
      - t3.small
      boot_types:
        - uefi-preferred
        - uefi
      cpu_options: []
    - region: us-gov-east-1
      partition: aws-us-gov
      arch: x86_64
      instance_names:
      - i3.large
      - t3.small
      boot_types:
        - bios
      cpu_options: []
    - region: us-gov-east-1
      partition: aws-us-gov
      arch: x86_64
      instance_names:
      - c5.large
      - m5.large
      - t3.small
      boot_types:
        - uefi-preferred
        - uefi
      cpu_options: []
test:
  img_proof_timeout: 600
upload:
  azure:
    max_retry_attempts: 5
    max_workers: 8
email_allowlist:
  emails@to.allow.com
domain_allowlist:
  suse.com
