jwt_algorithm: HS256
jwt_secret: enter-a-secret
log_dir: /var/log/mash/
encryption_keys_file: /var/lib/mash/encryption_keys
ssh_private_key_file: /var/lib/mash/ssh_key
amqp_host: localhost
amqp_user: guest
amqp_pass: guest
services:
  - obs
  - uploader
  - testing
  - replication
  - publisher
  - deprecation
  - pint
non_cred_services:
  - obs
credentials:
  credentials_directory: /var/lib/mash/credentials/
  accounts_file: /etc/mash/accounts.json
obs:
  download_directory: /var/lib/mash/images
provider:
  ec2:
    regions:
      aws:
        - ap-northeast-1
        - ap-northeast-2
        - ap-south-1
        - ap-southeast-1
        - ap-southeast-2
        - ca-central-1
        - eu-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - sa-east-1
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
      aws-cn:
        - cn-north-1
        - cn-northwest-1
      aws-us-gov:
        - us-gov-west-1
    helper_images:
      ap-northeast-1: ami-383c1956
      ap-northeast-2: ami-249b554a
      ap-southeast-1: ami-c9b572aa
      ap-southeast-2: ami-48d38c2b
      ap-south-1: ami-a6d1bac9
      ca-central-1: ami-21d76545
      cn-north-1: ami-bcc45885
      cn-northwest-1: ami-23978241
      eu-central-1: ami-bc5b48d0
      eu-west-1: ami-bff32ccc
      eu-west-2: ami-2a676d4
      eu-west-3: ami-7bc17406
      sa-east-1: ami-6817af04
      us-east-1: ami-4b814f22
      us-east-2: ami-71ca9114
      us-gov-west-1: ami-c2b5d7e1
      us-west-1: ami-d5ea86b5
      us-west-2: ami-f0091d9
testing:
  ipa_timeout: 600
uploader:
  azure:
    max_chunk_byte_size: 4096
    max_chunk_retry_attempts: 5
