jwt_algorithm: HS256
jwt_secret: enter-a-secret
log_dir: /var/log/mash/
private_key_file: /etc/mash/creds_key
services:
  - obs
  - uploader
  - testing
  - replication
  - publisher
  - deprecation
  - pint
non_cred_services:
  - obs
credentials:
  credentials_directory: /var/lib/mash/credentials/
jobcreator:
  accounts_file: /etc/mash/accounts.json
obs:
  download_directory: /var/tmp/mash/images
testing:
  ssh_private_key_file: /etc/mash/testing_key
