jwt_algorithm: HS256
jwt_secret: enter-a-secret
log_dir: /var/log/mash/
services:
  - obs
  - uploader
  - testing
  - replication
  - publisher
  - deprecation
  - pint
non_cred_services:
  - obs
credentials:
  credentials_directory: /var/lib/mash/credentials/
obs:
  download_directory: /var/tmp/mash/images
