jwt_algorithm: HS256
jwt_secret: enter-a-secret
log_dir: /var/log/mash/
encryption_keys_file: /var/lib/mash/encryption_keys
ssh_private_key_file: /var/lib/mash/ssh_key
amqp_host: localhost
amqp_user: guest
amqp_pass: guest
smtp_host: localhost
smtp_port: 25
smtp_ssl: False
smtp_user: test@fake.com
credentials_url: http://localhost:5006/
database_uri: sqlite:////var/lib/mash/app.db
services:
  - obs
  - upload
  - create
  - testing
  - raw_image_upload
  - replication
  - publisher
  - deprecation
non_cred_services:
  - obs
credentials:
  credentials_directory: /var/lib/mash/credentials/
obs:
  download_directory: /var/lib/mash/images
cloud:
  ec2:
    regions:
      aws:
        - af-south-1
        - ap-east-1
        - ap-northeast-1
        - ap-northeast-2
        - ap-south-1
        - ap-southeast-1
        - ap-southeast-2
        - ca-central-1
        - eu-central-1
        - eu-north-1
        - eu-south-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - me-south-1
        - sa-east-1
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
      aws-cn:
        - cn-north-1
        - cn-northwest-1
      aws-us-gov:
        - us-gov-east-1
        - us-gov-west-1
    helper_images:
      af-south-1: ami-0c6b5f01298bd1a1e
      ap-east-1: ami-024f2681e93e91a81
      ap-northeast-1: ami-383c1956
      ap-northeast-2: ami-249b554a
      ap-southeast-1: ami-c9b572aa
      ap-southeast-2: ami-48d38c2b
      ap-south-1: ami-a6d1bac9
      ca-central-1: ami-21d76545
      cn-north-1: ami-bcc45885
      cn-northwest-1: ami-23978241
      eu-central-1: ami-bc5b48d0
      eu-north-1: ami-4abe3234
      eu-south-1: ami-0c747453f89f809cd
      eu-west-1: ami-bff32ccc
      eu-west-2: ami-2a676d4
      eu-west-3: ami-7bc17406
      me-south-1: ami-021eb13384ade48e3
      sa-east-1: ami-6817af04
      us-east-1: ami-4b814f22
      us-east-2: ami-71ca9114
      us-gov-east-1: ami-43896f32
      us-gov-west-1: ami-c2b5d7e1
      us-west-1: ami-d5ea86b5
      us-west-2: ami-f0091d91
testing:
  img_proof_timeout: 600
uploader:
  azure:
    max_retry_attempts: 5
    max_workers: 8
email_whitelist:
  emails@to.allow.com
domain_whitelist:
  suse.com
