"""Password reset

Revision ID: b4dc33b1c274
Revises: 6a61895b8172
Create Date: 2020-03-24 11:58:33.232624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dc33b1c274'
down_revision = '6a61895b8172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_dirty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_dirty')
    # ### end Alembic commands ###
